name: Generate Daily PDF

on:
  workflow_dispatch:  # Manual trigger button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Markdown to PDF tool
      run: pip install markdown-pdf

    - name: Convert to PDF
      run: markdown-pdf summary-template.md

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: daily-summary
        path: summary-template.pdf
